### ISSUE TITLE
Change format of PublishDate in Post

### ISSUE THREAD

**Issue by bjornarjatten** [jokk-itu/PythonKindergarten#10]
PublishDate is currently an int, consider changing to DateTime

**Comment by jokk-itu** [comment]
Great idea, if it is allowed. 
Because the simulator depends on the current implementation of the API.

**Comment by bjornarjatten** [comment]
Moving to next weeks release

**Comment by bjornarjatten** [comment]
Moving to next weeks focused work

**Comment by bjornarjatten** [comment]
Moving to next weeks focused work

**Comment by bjornarjatten** [comment]
Cant make changes to API
