### ISSUE TITLE
Slet If(ErrorRaised) i frontend

### ISSUE THREAD

**Issue by jokk-itu** [jokk-itu/PythonKindergarten#21]
Denne form for kode skal slettes i pages, da der findes en Error.html der vises i stedet når der opstår fejl.
Tror nok der bare skal kastes en exception og så vil Blazor selv indlæse error.html og vise fejlbeskeden.

**Comment by jokk-itu** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-5.0&pivots=webassembly

Det her kan måske give lidt vejledning i hvordan fejl skal håndteres.

**Comment by bjornarjatten** [comment]
Moving to next weeks focused work
