### ISSUE TITLE
System.Threading.Tasks.ValueTask in "User Timeline"

### ISSUE THREAD

**Issue by bjornarjatten** [jokk-itu/PythonKindergarten#55]
Seems to come after you have been logged in, and then log out, and then access a user timeline page.

Screenshot of console:
![image](https://user-images.githubusercontent.com/20386318/111084660-d9360100-8513-11eb-8816-eceef8bf17a4.png)

**Comment by jokk-itu** [comment]
Authorization error when not logged in.
Will implement better error handling for this.
