### ISSUE TITLE
Error message when viewing userpage not logged in

### ISSUE THREAD

**Issue by bjornarjatten** [jokk-itu/PythonKindergarten#73]
![image](https://user-images.githubusercontent.com/20386318/111538411-ef8ac980-876c-11eb-962c-4efd39c5353b.png)

**Comment by jokk-itu** [comment]
Is it because the message should display a more descriptive message or not appear at all when the user isn't authorized to follow another user (Because they aren't logged in)?

**Comment by bjornarjatten** [comment]
I think it catches an exception which we do not need to show to end user

**Comment by jokk-itu** [comment]
Great i'll fix that
