### ISSUE TITLE
Roslynator discussion

### ISSUE THREAD

**Issue by jokk-itu** [jokk-itu/PythonKindergarten#76]
Setup errors when rules are broken or just warnings: https://github.com/JosefPihrt/Roslynator/blob/master/src/Analyzers/README.md

Setup refactorings or not: https://github.com/JosefPihrt/Roslynator/blob/master/src/Refactorings/README.md

**Comment by victornor** [comment]
Still awaiting a proper answer to the issue...
https://github.com/JosefPihrt/Roslynator/issues/775

**Comment by bjornarjatten** [comment]
Opened a new issue for this:
https://github.com/jokk-itu/PythonKindergarten/issues/113
